added faas-samples and bot-samples folders and one faas function
LivePersonInc/ConversationBuilder-Samples pull request #3
Opened 2021-08-05 18:39 UTC by cshape

Added on to our folder structure, added a faas function, and updated the readme.

2021-08-06 21:24 UTC, cshape commented
@dahby please take a look at the function and let me know if there's anything we should tidy up.

2021-08-06 21:45 UTC, dahby requested changes
Just a couple of things I'd recommend updating.

1. Include information on the "API_KEY" in secret storage and where that comes from.
2. Double check the error variable on the last line (should it be `error` instead of `err`?).

Aside from that, looks good!

2021-08-06 21:45 UTC, dahby commented on faas-samples/VIPcheck/README.md
> +- In Conversational Orchestrator, we'll have a Custom Function attribute (for this function) and a Policy which uses that attribute
```suggestion
- In Conversational Orchestrator, we'll have a Custom Function attribute (for this function) and a Policy which uses that attribute
```

Add reference to the "API_KEY" and how to add that to secret storage.

2021-08-06 21:45 UTC, dahby commented on faas-samples/VIPcheck/VIPcheck.js
> +        console.error(`Failed during secret operation with ${err.message}`);
If this is referencing the error in the current catch, it should read `${error.message}` instead of `{$err.message}`

2021-08-09 17:53 UTC, cshape commented
@dahby I've updated the PR to incorporate your change requests. please merge if all looks good to you.

2021-08-09 18:01 UTC, dahby approved these changes

2021-08-09 18:01 UTC, merged